[workspace]
# All the crates that make up this demo project
members = [
  "publisher",   # WebSocket server component
  "client",      # WebSocket client component
  "demo-runner", # Binary that runs both client and publisher
]

# Enable the version 2 feature resolver for cleaner dependency resolution
resolver = "2"

[workspace.dependencies]
futures = "*"
tokio = { version = "1.37.0", features = ["full"] }
tokio-tungstenite = "*"
tungstenite = "*"
thiserror = "*"
tracing = "*"
tracing-subscriber = "*"
